### ISSUE TITLE
Ctrl + Backspace doesn't work in muti-term.el

### ISSUE THREAD

**Issue by AAlvz** [emacsmirror/emacswiki.org#4]
Using `M -x multi-term` brings on a new terminal but when I try to delete backwards using `Ctrl + backspace` (to delete the complete word) the previous word is deleted but apparently it stays on the background. Here an example:

Write in the terminal
`$ mkdir `
Then type `Ctrl + backspace` so we get:
`$ `
and then typing `return` : 

mkdir: missing operand                                                                                  
Try 'mkdir --help' for more information.

I hope this is clear enough

**Comment by kensanata** [comment]
I don't think this is the right place to report bugs. Try and contact the author?

**Comment by AAlvz** [comment]
kensanata oh ok! ... I thought this was the correct place. I will remove it =)
